spring.datasource.url=jdbc:mysql://localhost:3306/p2l
spring.datasource.username=root
spring.datasource.password=lolita03
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
